### ISSUE TITLE
Issues to Explore 

### ISSUE THREAD

**Issue by juansvas** [maptimeLA/project-sandbox#16]
Meeting with Omar & Juan on Mon 11/16: (shoutout to La Monarca)

These are the issues to be considered for next steps. 
1. Create a blog using Github on updates and what has been learned at the project nights

2A) ID and create a table of all LA City agencies that own property - add to READ.ME
2B) Filter and create a geojson file
2C) Update map code to reflect new geojson 

3) Identify CSV files that can and can't be linked to geojson file, and note what is missing from those that can't be linked

**Comment by michaelkirk** [comment]
Hi @juansvas thanks for getting organized here. Do you mind if I break this up into several sub-issues that can be tackled separately?

**Comment by michaelkirk** [comment]
I've broken out the blog (#18) and city-parcel (#19) issues, but am not sure what to do with your third point. Can you spell it out, maybe with an example?

**Comment by cityhubla** [comment]
@michaelkirk, go ahead, we intended to split them into issues, the post here was for followup and comment on the discussion from Monday 11/16 in case additional issues should be raised.

**Comment by cityhubla** [comment]
Item 3, was based on the CSV datasets that Juan added, there's a moment where we last spoke at project night where you pointed to a CSV that had no APNs but mixed addresses. These would be hard to link to the parcel datasets. The idea was to see what each CSV contained and whether they can be linked to the attributes of the parcel dataset.

**Comment by cityhubla** [comment]
The [Prioritized Properties FY15-16.csv](https://github.com/maptimeLA/project-sandbox/blob/master/city_data/city/Prioritized%20Properties%20FY15-16.csv), could be linked because it contains the APN that can be matched to the public parcel set.

**Comment by michaelkirk** [comment]
Cool. Thanks @cityhubla! 

Did I capture it here? https://github.com/maptimeLA/project-sandbox/issues/20

**Comment by cityhubla** [comment]
perfect! thanks!

**Comment by michaelkirk** [comment]
I think this issue has been "completed" by delegation to #18, #19 and #20.

**Comment by cityhubla** [comment]
Sounds good, thanks for the help!
