### ISSUE TITLE
What items to add to README

### ISSUE THREAD

**Issue by cityhubla** [maptimeLA/project-sandbox#2]
Post here for links, notes and research on case studies, articles.

**Comment by machikoyasuda** [comment]
Best practice lists:
- https://pages.18f.gov/open-source-guide/github-repo-checklist/
- https://pages.18f.gov/content-guide/

**Comment by machikoyasuda** [comment]
How about: "How can we use GitHub to transparently collaborate between government and the public?"
1. What can government do:
2. What can the public do:
3. What can we both do:

## Words
- Write better documentation: https://pages.18f.gov/open-source-guide/github-repo-checklist/
- Write better copy: https://pages.18f.gov/content-guide/
- Provide definitions for confusing terms and links to learn more. Provide links to the actual laws/where these are actually defined if people want to learn more.

## Data
- Format data and spreadsheets without using so many acronyms/abbreviations/jargon. 
- What are better file formats?

**Comment by cityhubla** [comment]
### Introduction (draft)

This developing guide helps organizations document civic projects, non-code and code, with public collaboration and participation using the services and resources of Github. The documentation written should be clear for both audiences and participants as suggested from the [18F Open Style Guide](https://pages.18f.gov/open-source-guide/index.html).

### Outcomes

`insert language`

### Project Types (What kind of projects can this be used for?)
- Open-source tools using open data projects for
  - Visualizing data through maps, graphs
  - Reporting data inaccuracies
  - Create user-feedback

### Uses
1. What can government do:
2. What can the public do:
3. What can we both do:

### Words
- Write better documentation: https://pages.18f.gov/open-source-guide/github-repo-checklist/
- Write better copy: https://pages.18f.gov/content-guide/
- Provide definitions for confusing terms and links to learn more. Provide links to the actual laws/where these are actually defined if people want to learn more.

### Data
- Format data and spreadsheets without using so many acronyms/abbreviations/jargon. 
- What are better file formats?

**Comment by cityhubla** [comment]
We need to update the readme to separate the exploration from the project itself, that the project will allow for explorations between gov and community.

**Comment by cityhubla** [comment]
This would allow project sandbox to be developed further with the outcomes from the first one in regards to documentation, tracking and management and become the improved template for new explorations.

**Comment by machikoyasuda** [comment]
added the 18f links into the wiki instead and going to close this for now.

**Comment by michaelkirk** [comment]
:+1: for using the wiki for more documentation. The README.md was getting unwieldy. It should be like a "frontpage" to contributing to the project.
