### ISSUE TITLE
Geocode non-geocoded datasets

### ISSUE THREAD

**Issue by michaelkirk** [maptimeLA/project-sandbox#20]
(extracted from #16)

We want to map all the unused parcels that we know about, but some of our parcel data is not in a format readily mappable. E.g. at least one of our datasources is a spreadsheet with addresses, but we need something more like a latitude/longitude to be able to put it on a map. In other words, we need to [geocode](https://en.wikipedia.org/wiki/Geocoding) some of our data.
- [ ] Which datasets are not geocoded?
- [ ] What, if anything, needs to be done to geocode them? (make separate issues as appropriate)

Common approaches might be:
1. Does it have an address we can process in a geocoding service? (e.g. google has something...)
2. Does it have an APN we could link to an existing parcel with a known lat/lon or better yet, is there an APN geocoding service in LA?

**Comment by michaelkirk** [comment]
One thing I'm trying to get better at solving generally is a workflow for taking some raw data from some "authoritative" source and transforming it into something useful (which can be multiple steps), but doing it in such a way that explains where your data came from and exactly what you did to it in order to get what you wanted. 

Something like a "data" catalog. Really it could be as simple as a TOC.md in the data/ folder with a line or two about the progeny of each file.

**Comment by michaelkirk** [comment]
woops. Didn't mean to close. FYI I'm working on this this afternoon.

**Comment by juansvas** [comment]
@michaelkirk i started up a table listing which files have ains & addresses & not. I can geocode the ones we have addresses for - do you recommend a particular service? i usually use http://www.gpsvisualizer.com/ but it only takes batches of less than 500 so i'm wondering what's a better tool for the assessor files (7K+ records)

**Comment by juansvas** [comment]
@michaelkirk @machikoyasuda @cityhubla Quick update on progress that's happened on our end... we're working with Compiler LA to create one centralized, deduped and cleansed workbook of all City-owned properties and showing which of the many lsits that we have they all appear on. That should be done within the next 2 weeks. 

I know my team and I have struggled to keep continuity going so perhaps we can boil down the way we collaborate to way more specific questions (which will be easier to answer w the centralized book)?

**Comment by michaelkirk** [comment]
Hey that's good news @juansvas! Happy to help if you have a work-party.
