### ISSUE TITLE
How to make pull requests for different items

### ISSUE THREAD

**Issue by cityhubla** [maptimeLA/project-sandbox#6]
Suggested ways of branching / making pull requests (Possible addon to readme)

I want to **change/modify/update | add | remove**   a   **document | exhibit | dataset | code**
1. You must branch from master and label your branch the of what you will change
2. Make your adjustments and make a pull request the labeling `<name of adjustment case> of <name of object in question>`
3. Review and comments will be made to your pull request.
4. After peer review, pull request is allowed to merge to master

**Comment by machikoyasuda** [comment]
![screen shot 2015-11-08 at 3 08 23 pm](https://cloud.githubusercontent.com/assets/3673236/11023332/961c589e-862a-11e5-8588-1cfe90621fa8.png)

**Comment by JRHutson** [comment]
When I first started dealing with pull requests I found it confusing trying to figure out which branch should be the base and which should be the head. It could be useful to clarify in the readme that the Base is the branch you want to update with the pull request.

**Comment by machikoyasuda** [comment]
I added instructions to the README.md on how to make PRs from Github.com 

I think this is less confusing for now!

**Comment by juansvas** [comment]
That works for images and XLS, but not for CSV files. I can add an XLS with
the individual tabs and a master, but I don't want to create extra work if
those will then have to be converted over to CSV. Strange that CSVs can be
uploaded through local but not browser

On Thu, Nov 12, 2015 at 12:49 PM, Machiko Yasuda notifications@github.com
wrote:

> I added instructions to the README.md on how to make PRs from Github.com
> 
> I think this is less confusing for now!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maptimeLA/project-sandbox/issues/6#issuecomment-156229718
> .

## 

Juan Sebastian Vasquez
vasquezsays.com
